<?php
 
defined("_VALID_ACCESS") || die('Direct access forbidden');
 
class Custom_RMACommon extends ModuleCommon {
 
	// display module on menu
	public static function menu() {
	
		return array(__('CRM')=>array('__submenu__'=>1,__('RMA')=>array()));
	}
	
	// function to get rma_id from database
	public static function display_rma_id($r, $nolink) {
        return Utils_RecordBrowserCommon::create_linked_label_r('custom_rma', 'rma_id', $r, $nolink);
    }
	
	// function to automatically generate unique rma_id code to tell the customer
	public static function generate_id($date, $id) {
        if(is_array($id)) $id = $id['id'];
        return 'RMA'.date('Y', strtotime($date)).str_pad($id, 5, '0', STR_PAD_LEFT);
   }

	// function called after insert new element in order to add autogenerated rma_id based on year of request and id
    public static function process_request($data, $mode) {
        switch($mode) {
            case 'adding':
                $data['active']=true;
                break;
            case 'added':
				Utils_RecordBrowserCommon::update_record('custom_rma',$data['id'],array('rma_id'=>self::generate_id($data['request_date'], $data['id'])), false, null, true);
                break;
            default:
                break;
        }
        return $data;
    }
	
	// function to search in records. This build up query string and return records found
	public static function search($word){
        $ret = array();
        $limit_per_recordset = Base_SearchCommon::get_recordset_limit_records();
        if(Utils_RecordBrowserCommon::get_access('custom_rma','browse')) {
            $wo = explode(' ', $word);

            $crits = array();
            foreach ($wo as $w)
                $crits = Utils_RecordBrowserCommon::merge_crits($crits, array(
					'"~rma_id'=>DB::Concat(DB::qstr('%'),DB::qstr($w),DB::qstr('%')), 
					'|"~customer'=>DB::Concat(DB::qstr('%'),DB::qstr($w),DB::qstr('%')),
					'|"~manufacturer'=>DB::Concat(DB::qstr('%'),DB::qstr($w),DB::qstr('%')),
					'|"~device_sku'=>DB::Concat(DB::qstr('%'),DB::qstr($w),DB::qstr('%')),
					'|"~serial_number'=>DB::Concat(DB::qstr('%'),DB::qstr($w),DB::qstr('%'))
				));

            $result = self::get_contacts($crits, array(), array(), $limit_per_recordset);

            foreach ($result as $row)
                $ret[] = Utils_RecordBrowserCommon::record_link_open_tag('custom_rma', $row['id']).__( 'RMA #%d, %s %s', array($row['id'], $row['rma_id'], $row['device_sku'])).Utils_RecordBrowserCommon::record_link_close_tag();
        }

        return $ret;
    }
}
 
?>